import assert from "node:assert/strict";
import test from "node:test";
import {
  categorizeBlocker,
  promotionBlockers,
  summarizeBlockerCategories
} from "../scripts/promotion-blockers.mjs";

const today = new Date(2026, 5, 14);
const validHash = `sha256:${"a".repeat(64)}`;

function baseRow(overrides = {}) {
  return {
    workflow_status: "approved",
    confidence_status: "verified",
    review_decision: "approved",
    reviewed_by: "operator",
    reviewed_at: "2026-06-14",
    deal_id: "deal-test",
    candidate_id: "cand-test",
    restaurant_id: "restaurant-test",
    source_id: "source-test",
    source_capture_id: "capture-test",
    direct_confirmation_id: "",
    source_check_id: "check-test",
    source_url: "https://example.com/specials",
    public_title: "Test lunch special",
    public_description: "A reviewed food-only lunch special.",
    source_quote: "Official lunch special details.",
    evidence_summary: "Official source captured by operator.",
    content_hash: validHash,
    next_check_due: "2099-01-01",
    expires_on: "2099-01-02",
    review_task_id: "review-test",
    evidence_captured_at: "2026-06-14",
    last_verified_at: "2026-06-14",
    decision_reason: "Official source, reviewed copy, food-only.",
    published_at: "2026-06-14",
    dine_in: "true",
    takeout: "false",
    delivery: "false",
    conflict_detected: "false",
    public_copy_approved: "true",
    mvp_publish_eligible: "true",
    source_tier: "tier_1_official",
    screenshot_path: "fixtures/prototype/evidence/test-special.png",
    archive_url_or_path: "",
    evidence_url_or_path: "",
    hidden_at: "",
    is_live_data: "false",
    fixture_data_class: "verified_static",
    prototype_notice: "Static prototype data.",
    alcohol_classification: "food_only",
    location_scope_status: "wilmington_confirmed",
    source_name: "Official website",
    evidence_type: "official website",
    ...overrides
  };
}

test("official reviewed food-only row is promotable", () => {
  const result = promotionBlockers(baseRow(), today);

  assert.deepEqual(result.blockers, []);
  assert.deepEqual(result.fieldsNeeded, []);
});

test("probable confidence is blocked for public fixture promotion", () => {
  const result = promotionBlockers(baseRow({ confidence_status: "probable" }), today);

  assert.equal(result.blockers.includes("confidence_status is not verified"), true);
  assert.equal(result.fieldsNeeded.includes("confidence_status"), true);
});

test("non-official source tier is blocked and categorized as source tier", () => {
  const blocker = "tier_4_secondary is not accepted by the current public fixture validator";
  const result = promotionBlockers(baseRow({ source_tier: "tier_4_secondary" }), today);

  assert.equal(result.blockers.includes(blocker), true);
  assert.equal(categorizeBlocker("missing source_tier"), "source tier");
  assert.equal(categorizeBlocker(blocker), "source tier");
});

test("AI evidence text is blocked as evidence", () => {
  const result = promotionBlockers(baseRow({ source_quote: "Generated by ChatGPT from menu notes." }), today);

  assert.equal(result.blockers.includes("row appears to rely on AI/GPT output as evidence"), true);
  assert.equal(result.fieldsNeeded.includes("source_quote"), true);
});

test("expired and overdue dates are blocked", () => {
  const result = promotionBlockers(baseRow({
    expires_on: "2026-06-13",
    next_check_due: "2026-06-13"
  }), today);

  assert.equal(result.blockers.includes("expires_on is expired"), true);
  assert.equal(result.blockers.includes("next_check_due is overdue"), true);
});

test("metadata-only gaps are identifiable by category summary", () => {
  const result = promotionBlockers(baseRow({
    is_live_data: "",
    fixture_data_class: "",
    prototype_notice: ""
  }), today);
  const summary = summarizeBlockerCategories([{ id: "deal-test", blockers: result.blockers }]);

  assert.deepEqual(result.blockers.toSorted(), [
    "fixture_data_class must be verified_static for public prototype fixtures",
    "is_live_data must be false for public prototype fixtures",
    "missing prototype_notice required by current fixture validator"
  ].toSorted());
  assert.deepEqual(summary, [{
    category: "fixture metadata",
    count: 3,
    blockers: [
      {
        blocker: "fixture_data_class must be verified_static for public prototype fixtures",
        count: 1
      },
      {
        blocker: "is_live_data must be false for public prototype fixtures",
        count: 1
      },
      {
        blocker: "missing prototype_notice required by current fixture validator",
        count: 1
      }
    ]
  }]);
});
